### ISSUE TITLE
As a teacher, I want to be able to create and edit lessons so that I can produce educational content for my students.

### ISSUE THREAD

**Issue by bnbaltz** [CEN3031-Team-9D/diamond-code-sparks#10]
Acceptance Criteria:
- [x] User can access a "Create Lesson" button from the teacher dashboard.
- [x] User can save, update, or cancel lesson creation.
- [x] User is presented with an editor interface where text, images, and multimedia can be inserted

Tasks:
- [x] Create lesson button on teacher dashboard
- [x] Create a page with editor for user 
- [x] Allow users to update, save, cancel

Wireframes:
![Image](https://github.com/CEN3031-Team-9D/diamond-code-sparks/assets/15271479/42d85c0c-c486-475a-ac6d-c9baef5c0937)

**Comment by butakow** [comment]
I've performed unit and integration testing for the changes linked in the PR by trying all of the functionality on the dashboard page before successfully merging into the develop branch. I've also performed static testing through SonarCloud, ensuring that there are no issues with my commits.

**Comment by butakow** [comment]
Next steps have been moved to user story #3.
