### ISSUE TITLE
As a teacher, I want a reliable place to store my lessons so that I can access them whenever needed.

### ISSUE THREAD

**Issue by bnbaltz** [CEN3031-Team-9D/diamond-code-sparks#5]
Acceptance Criteria
- [x] User can save lessons without encountering errors.
- [x] Saved lessons are retrievable from the "View Lessons" page.

Tasks
- [x] Save lessons without encountering errors
- [x] Allow lessons to be retrievable 
- [x] Create a database to store data

**Comment by butakow** [comment]
I've performed unit and integration testing for the changes linked in the PR by trying all of the implemented functionality before and after merging Chris's previous changes to the dashboard page. I've also performed static testing through SonarCloud, ensuring that there are no issues with my commits.

Next steps and associated wireframes will be added to closely linked user story #10.
